export const types = {
    GET_MEDIA: "GET_MEDIA",
    GET_MEDIA_SUCCESS: "GET_MEDIA_SUCCESS",
    GET_MEDIA_TIMEOUT: "GET_MEDIA_TIMEOUT",
    DELETE_MEDIUM: "DELETE_MEDIUM",
    DELETE_MEDIUM_SUCCESS: "DELETE_MEDIUM_SUCCESS",
    DELETE_MEDIUM_ERROR: "DELETE_MEDIUM_ERROR"
};
