export const types = {
    ADD_MEDIUM: "ADD_MEDIUM",
    ADD_MEDIUM_SUCCESS: "ADD_MEDIUM_SUCCESS",
    ADD_MEDIUM_ERROR: "ADD_MEDIUM_ERROR",
    EDIT_MEDIUM: "EDIT_MEDIUM",
    EDIT_MEDIUM_SUCCESS: "EDIT_MEDIUM_SUCCESS",
    EDIT_MEDIUM_ERROR: "EDIT_MEDIUM_ERROR",
    GET_MEDIA: "GET_MEDIA",
    GET_MEDIA_SUCCESS: "GET_MEDIA_SUCCESS",
    GET_MEDIA_TIMEOUT: "GET_MEDIA_TIMEOUT",
    DELETE_MEDIUM: "DELETE_MEDIUM",
    DELETE_MEDIUM_SUCCESS: "DELETE_MEDIUM_SUCCESS",
    DELETE_MEDIUM_ERROR: "DELETE_MEDIUM_ERROR",
};
